config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users
  root to: 'transportation_footprint#index'
  get 'transportation_footprint', to: 'transportation_footprint#index'
  post 'transportation_footprint', to: 'transportation_footprint#save_transportation_footprint'
  get 'shower_usage', to: 'shower_usage#index'
  post 'shower_usage', to: 'shower_usage#save_shower_usage'
  get 'user_footprints', to: 'user#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shower_usage.rb
class ShowerUsage < ApplicationRecord
    belongs_to :user
end

app/models/transportation_footprint.rb
class TransportationFootprint < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transportation_footprints
  has_many :shower_usages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/shower_usage_controller.rb
class ShowerUsageController < ApplicationController
    skip_before_action :verify_authenticity_token
    layout "shower_usage"

    def index
        @user = current_user
        @user_props = { 
            first_name: @user.first_name,
            last_name: @user.last_name,
            email: @user.email,
            user_id: @user.id 
        }
    end

    def save_shower_usage
        new_shower_usage = ShowerUsage.create!(shower_usage_params)
        if new_shower_usage
            render json: new_shower_usage
        else
            render json: new_shower_usage.errors
        end
    end

    private

    def shower_usage_params
        params.permit(:user_id, :minutes, :daily_gallons, :yearly_gallons)
    end
end

app/controllers/transportation_footprint_controller.rb
class TransportationFootprintController < ApplicationController
    skip_before_action :verify_authenticity_token
    layout "transportation_footprint"

    def index
        @user = current_user
        @user_props = { 
            first_name: @user.first_name,
            last_name: @user.last_name,
            email: @user.email,
            user_id: @user.id 
        }
    end

    def save_transportation_footprint
        new_carbon_footprint = TransportationFootprint.create!(transportation_footprint_params)
        if new_carbon_footprint
            render json: new_carbon_footprint
        else
            render json: new_carbon_footprint.errors
        end
    end

    private

    def transportation_footprint_params
        params.permit(:user_id, :mpg, :miles_driven_per_year, :metric_ton_carbon_dioxide_output)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if current_user
      @current_user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shower_usage_helper.rb
module ShowerUsageHelper
end

app/helpers/transportation_footprint_helper.rb
module TransportationFootprintHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Green Max</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shower_usage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shower Usage Calculator</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'shower-usage-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/transportation_footprint.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carbon Footprint Calculator</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'transportation-footprint-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shower_usage/index.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "logout-button") %>
  <%= link_to('Transportation footprint', transportation_footprint_path, method: :get, class: "logout-button") %>
  <%= link_to('All', user_footprints_path, method: :get, class: "logout-button") %>
<% else %>
  <%= link_to('Login', new_user_session_path) %>
<% end %>
<%= react_component("ShowerUsage", props: @user_props, prerender: false) %>

app/views/transportation_footprint/index.html.erb
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "logout-button") %>        
<% else %>
  <%= link_to('Login', new_user_session_path) %>  
<% end %>
<%= react_component("TransportationFootprint", props: @user_props, prerender: false) %>

app/views/user/index.html.erb
<h1>Saved footprints</h1>
<p>Showers</p>
<% @current_user.shower_usages.map do |su| %>
Minutes: <%= su.minutes %>
Daily Gallons: <%= su.daily_gallons %>
Yearly Gallons: <%= su.yearly_gallons %>
<% end %>
<br />
<br />
<p>Transportation Footprints</p>
<% @current_user.transportation_footprints.map do |tp| %>
MPG: <%= tp.mpg %>
Miles driven per year: <%= tp.miles_driven_per_year %>
Metric Tons Per Year: <%= tp.metric_ton_carbon_dioxide_output %>
<% end %>